title: Is TV minding its 'P's and 'Q's?
description: This site is for exploring how television uses typography
header_text: ""
footer_text: Copyright 2020 Casey Grenfell
header_feature_image: ../uploads/bannerblogfinal.png
bannerheight: 40vmax
logo: ../uploads/logofinal.png
favicon: ../uploads/finalfavi.png
gridlayout: false
fixednavbar: false
upzoom: true
