title: Casey Grenfell
description: This site is for exploring how television uses typography
header_text: ""
footer_text: Copyright 2020 Casey Grenfell
header_feature_image: ../uploads/bannerblog.png
bannerheight: 20vmax
logo: ../uploads/bloglogo2.png
favicon: ../uploads/blog-favicon.png
gridlayout: false
fixednavbar: false
upzoom: true
