title: Is TV minding its 'P's and 'Q's?
description: This site is for exploring how television uses typography
header_text: ""
footer_text: Copyright 2020 Casey Grenfell
header_feature_image: ../uploads/my-post-5-.png
bannerheight: 20vmax
logo: ../uploads/logonew21.png
favicon: ../uploads/finalfavi.png
gridlayout: true
fixednavbar: false
upzoom: true
