title: Does TV mind its 'P's and 'Q's?
description: This site is for exploring how television uses typography
header_text: ""
footer_text: Copyright 2020 Casey Grenfell
header_feature_image: ../uploads/bannerblog3.png
bannerheight: 20vmax
logo: ../uploads/bloglogo4.png
favicon: ../uploads/newfavicon-16x16.png
gridlayout: false
fixednavbar: false
upzoom: true
