title: Does TV mind its 'P's and 'Q's?
description: This site is for exploring how television uses typography
header_text: ""
footer_text: Copyright 2020 Casey Grenfell
header_feature_image: ../uploads/bannerblognew.png
bannerheight: 20vmax
logo: ../uploads/bloglogo6.png
favicon: ../uploads/newfavi.png
gridlayout: false
fixednavbar: false
upzoom: true
